РК 1
go-park-mail-ru/2020_2_Konami pull request #1
Opened 2020-10-07 17:06 UTC by mr-okto

2020-10-07 21:46 UTC, hackallcode requested changes

2020-10-07 21:46 UTC, hackallcode commented on server/server.go
> +	errMsg := `{"error": "` + msg + `"}`
Так очень плохо делать, так как если строка будет содержать, например, ковычку, все сломается. Надо создать структуру и ее json encode

2020-10-07 21:46 UTC, hackallcode commented on server/server.go
> +	i := 0
Зачем тут и в аналогичных местах выносится индекс? Можно же просто сделать  for i, value, тем более порядок тут не важен

2020-10-07 22:03 UTC, mr-okto commented on server/server.go
> +	i := 0
Там id не серийный, а случайный.
https://github.com/go-park-mail-ru/2020_2_Konami/blob/b9ed9eb7705bfbbf98d3ad08e30bb89cab74ed8f/server/server.go#L186

2020-10-08 08:10 UTC, hackallcode requested changes

2020-10-08 08:10 UTC, hackallcode commented on server/go.mod
> +module github.com/go-park-mail-ru/2020_2_Konami
Прикол но модулей в том, что можно любое название сделать и использовать его во всем проекте для подтягивания соседних файлом из проекта по абсолютной пути. Так что давай сделаем название в одно слово)

2020-10-08 09:40 UTC, hackallcode approved these changes

2020-10-08 09:40 UTC, merged